### PR TITLE
Usb support

### PR DESCRIPTION
**Pull request by GwendalRaoul**
This PR is for sharing the code and testing it. It will not be merged directly but will be officially released in next SDK release (Rel 1.1.0 probably).

# How to build
By default the dualmcu-app will be built with standard uart.

In order to choose the uart through USB (only available for nrf52833 and nrf52840 based boards) it has to be explicitly required.

## From cmd line
`make app_name=dualmcu_app target_board=pca10056 uart_use_usb=yes -j7`

## In board definition
https://github.com/wirepas/wm-sdk/blob/24f52319ef1954c5f4cf58548d04ab0229f52c03/board/mdbt50q_rx/config.mk#L5

# How to customize
Few parameters must be set in final product to define USB vendor ID, manufacturer and product string.
Product id is automatically generated but can be modified too if needed.

Here is an example:
https://github.com/wirepas/wm-sdk/blob/24f52319ef1954c5f4cf58548d04ab0229f52c03/board/mdbt50q_rx/config.mk#L7-L10

Those options can also be set from cmd line.

# Uart speed
In many Wirepas tools, the uart speed is required. In case of UART through USB, this information is discarded and can be set to any value (like in sinkService or Wirepas Terminal)

# Known issues
## Reboot of board
When node configuration is changed with remote API, or if the node controlled through USB UART is stopped, it creates a reboot of the board (by design).
In case of USB connection, it means that the connection will drop and the board will enumerate again (~1s).

There is patch here for the gateway (c-mesh-api): https://github.com/wirepas/c-mesh-api/pull/29
In order to test it a new sinkService must be built.
For Wirepas Terminal, the connection will drop but can be reopen with File->Reopen last connection

### CODE REVIEW

**Comment by bencorrado** [comment]
Recommend we remove the random PID generation as this is not recommended practice for USB devices.

Recommend we modify pca10059 to include 'uart_use_usb' by default

Recommend we add documentation update to explain how it should be used.

**Comment by bencorrado** [comment]
DCDC for REG0 is not running (confirmed with oscilloscope on L4 of PCA10059), leaving VDD_nRF at at state where brownouts can happen with LED usage.

**Comment by bencorrado** [comment]
To make the device unique instead of a random PID, I suggest in `mcu/nrf52/hal/usb_uart/usb_descriptors.c` on line 65 changing `.iSerialNumber      = 0x03,` to be generated unique per device.

**Comment by GwendalRaoul** [comment]
> 
> 
> To make the device unique instead of a random PID, I suggest in `mcu/nrf52/hal/usb_uart/usb_descriptors.c` on line 65 changing `.iSerialNumber = 0x03,` to be generated unique per device.

This is already the case if you look at line 146 in same file. I modified a bit the sample code from tinyusb for this part.

**Comment by GwendalRaoul** [comment]
> 
> 
> Recommend we remove the random PID generation as this is not recommended practice for USB devices.
> 
So you would prefer a define like usb_vid?
> Recommend we modify pca10059 to include 'uart_use_usb' by default
> 
Yes it is a good idea

> Recommend we add documentation update to explain how it should be used.
With more or less the content from this PR description?

**Comment by GwendalRaoul** [comment]
Available from 1.1.0 release.

**Pull request closed without merging**
